lua/rust-tools/inlay_hints.lua

Thanks for this nice plugin! I've found a small issue to you could maybe investigate.
I'm using the latest master of rust-analyzer (built yesterday). When I open a rust file in the moment rust-analyzer starts up (like right after file open) it will return the numeric value `0` as a result of `rust-analyzer/inlayHints`. After some start-up time, indexing time it will return the expected table.
This fix would work for me. Maybe you could have a look whether there's a better solution.

Ensure that result is table in parseHints

---

lua/rust-tools/config.lua
lua/rust-tools/inlay_hints.lua

Using the same color as the comments can be confusing a bit, the ability to change the color would be a nice addition.

Add config option to change the color of inlay hints

---

lua/rust-tools/runnables.lua

One of my projects had a space in the path name, which caused `runnables` to fail.

make runnables work on paths with spaces

---

lua/rust-tools/runnables.lua

Update run_command calls in handler and get_telescope_handler functions to reflect change from run_command to M.run_command.

Fix run_command calls

---

lua/rust-tools/hover_actions.lua
lua/rust-tools/runnables.lua

some people will remap ':' to ';' and vice verse (or other similar bindings), in such case runnable would not be able to run.

add noremap=true

---

README.md

Easier for new users to know how to configure the color of inlay_hints (e.g. set it to be different from `Comment`)

add inlay_hints.highlight option to README doc

---

README.md
lua/rust-tools.lua
lua/rust-tools/hover_range.lua

Hi,
The latest release of rust-analyzer added the ability to view the type of selected code in visual mode while hovering.
I really wanted that to be enabled in neovim and hacked something together :smile: .
I added a new command `RustHoverRange` and an experimental capability which will do the work of making the request. It uses the default hover handler for better integration with the hover actions.
I added the new command to the documentation, but did not make a gif of how it works (didn't know how :cry: )
Here some extra links:
* [PR hoverRange in rust-analyzer with example gif](https://github.com/rust-analyzer/rust-analyzer/pull/9693)
* [Specification of the protocol in rust-analyzer](https://github.com/rust-analyzer/rust-analyzer/blob/master/docs/dev/lsp-extensions.md#hover-range) …

Add hoverRange capability

---

README.md
lua/rust-tools.lua
lua/rust-tools/config.lua
lua/rust-tools/crate_graph.lua
lua/rust-tools/utils/utils.lua

Hi @simrat39 ,
I implemented the view crate graph-feature. It is based around `rust-analyzer/viewCrateGraph` method and pipes the result to the `dot`-command from graphviz to show the graph.
I added the option to chose the backend and file output in the global config and optionally in the command `:RustViewCrateGraph` (more info in the `README.md`).
This introduces a new requirement for the `dot`-command in a posix-shell, but I tried to make it so that only when using this new feature an error might occur.
To enable auto completion and better sanitazation of the command arguments, I added a list of all the current backends in `graphviz` (`config.lua` and `README.md`) and used it in `rust-tools.lua` and `crate_graph.lua`. This list is hardcoded and may need to be changed when graphviz …

Add ViewCrateGraph ability

---

lua/rust-tools/hover_actions.lua

I noticed whenever I close the popup window with escape, `:lua require'rust-tools.hover_actions'._close_hover()<CR>` gets printed to the status line – given that function isn't documented and it starts with an underscore, I guess it's meant to be internal and shouldn't be exposed to the user, and anyway it's not very useful to see that every time I close the popup.
Making the mappings `<silent>` stops the command being echoed to the status line.

don't echo commands in mappings

---

lua/rust-tools/inlay_hints.lua

Inlay hints weren't applying the underlying highlight from the cursorline. Setting `hl_mode="combine"` for the extmark fixes this

Fix highlight mode for inlay hints

---

lua/rust-tools/code_action_group.lua
lua/rust-tools/dap.lua
lua/rust-tools/runnables.lua
lua/rust-tools/utils/utils.lua

&& isn't supported in Powershell or cmd on Windows. Ideally we'd use a `;` instead of a `|`, but it doesn't work for whatever reason.
`vim.loop.os_uname().sysname == "Windows"` seems to be the standard for detecting if the OS is Windows, but for whatever reason I get "Windows_NT" on my system, so I added it as well.
It does complain about `The filename, directory name, or volume label syntax is incorrect.` when I run a runnable, but it still seems to work fine.

Make runnables work on Windows

---

lua/rust-tools/standalone.lua

The arguments with which `on_attach` is currently called are in the wrong order in this plugin
https://github.com/neovim/nvim-lspconfig/blob/d0263c11e53086242eea72cb76db9fecc6fbc449/lua/lspconfig/configs.lua#L256-L258
The client is the first argument and buffer number the second, rather than being the other way around as was originally done here.

fix(standalone): call `on_attach` with correct argument order

---

lua/rust-tools/executors/init.lua
lua/rust-tools/executors/toggleterm.lua

After run, `toggleterm` will be closed by pressing any key.
Type `<C-\><C-n>` to enter normal mode.
This process can be automated.
```lua
Terminal:new({
-- dir, cmd, close_on_exit ...
on_open = function(t)
-- enter normal mode
vim.api.nvim_feedkeys(vim.api.nvim_replace_termcodes([[<C-\><C-n>]], true, true, true), "", true)
-- (optional) set close shortcut
vim.api.nvim_buf_set_keymap(t.bufnr, "n", "q", "<cmd>close<CR>", { noremap = true, silent = true })
end
})
```
Do you think it's better to add this?

feat(executor): Add toggleterm

---

README.md
lua/rust-tools/config.lua
lua/rust-tools/inlay_hints.lua

This PR adds an option for showing a variable name before type hints so we can easily distinguish multiple types of variables at the same line or between type hints and chaining hints. By default, it's disabled.

Add option for showing variable name before type hints

---

README.md

Just a small README update to make it easier to find the Codelldb path on a unix-line machine

Update CodeLLDB path using unix environment variables

---

lua/rust-tools/join_lines.lua
lua/rust-tools/move_item.lua

This fixes RustMoveItemUp/Down and RustJoinLines

add bufnr and offset_encoding arguments to join_lines and move_items

---

lua/rust-tools/code_action_group.lua

vim.api.nvim_buf_* and vim.api.nvim_win_* no longer convert a nil buffer/window argument to 0.
So we must explicitly use `or 0` ourselves

fix RustCodeAction

---

README.md
lua/rust-tools/config.lua
lua/rust-tools/server_status.lua

Addresses a common issue with large workspaces that take longer to load and cause errors such as:
https://github.com/rust-analyzer/rust-analyzer/issues/10910
https://www.reddit.com/r/neovim/comments/qwlheb/delay_vimlspcodelensrefresh_until_rustanalyzer_is/
This works by allowing passing a callback to be run once `serverStatus` with `quiescent` is sent (similar to inlayHints)
An example configuration:
```lua
tools = {
on_initialized = function()
vim.cmd([[
augroup SuperDuperAus
autocmd CursorHold                      *.rs silent! lua vim.lsp.buf.document_highlight()
autocmd CursorMoved,InsertEnter         *.rs silent! lua vim.lsp.buf.clear_references()
autocmd BufEnter,CursorHold,InsertLeave *.rs silent! lua vim.lsp.codelens.refresh()
autocmd BufWritePre                     *.rs silent! …
```

Add on_initialized hook

---

lua/rust-tools/hover_actions.lua

Adds a "empty map" check on the border.
Previously, if the user removed the border with `border = {}`, the script would crash.
Else, if the user tried to remove the border with `border = nil`, the default config would kick in, essentially overriding the user's configuration.

Fix nil border

---

lua/rust-tools/inlay_hints.lua

Strip all occurrences of `: ` which by itself would not be a valid Rust token stream. But yet, I hate myself for it.
Fixes: #158

fix(inlay_hints): Horribly fix chaining hints issue

---

lua/rust-tools/inlay_hints.lua

This seems to fix the issue I described in #161. I feel a bit like this should possibly be considered a bug in neovim itself, but I figured either way this workaround might be useful here too.

fix(inlay_hints): Stop nvim from rendering wrong characters

---

lua/rust-tools/code_action_group.lua

This is broke in PR 17814: https://github.com/neovim/neovim/pull/17814.

Fix outdated capabilities access

---

README.md
lua/rust-tools.lua
lua/rust-tools/external_docs.lua

I recently discovered a solution for the problem I had already exists inside rust-analyzer ( https://github.com/rust-lang/rust-analyzer/pull/5917 ). 
This adds the command to this plugin. 
I'm happy to apply any needed changes.

add RustOpenExternalDocs to open docs for element under the cursor 

---

lua/rust-tools/debuggables.lua
lua/rust-tools/runnables.lua

When I have another lang server active that doesn't register any runnables/debuggables the result comes back nil, this nil value is then passed along to a function that tries to loop over the nil value.

fix: nil check for runnable and debuggable handler methods closes #217

---

lua/rust-tools/code_action_group.lua
lua/rust-tools/hover_actions.lua
lua/rust-tools/utils/utils.lua

Hello! I've been running into issues like these (admittedly because I sometimes hijack the hover buffer contents into a different preview window): 
```
E5108: Error executing lua ...r/start/rust-tools.nvim/lua/rust-tools/hover_actions.lua:38: Invalid window id: 1051
stack traceback:
[C]: in function 'nvim_win_close'
...r/start/rust-tools.nvim/lua/rust-tools/hover_actions.lua:38: in function '_close_hover'
[string ":lua"]:1: in main chunk
```
I figured something like this would make sense? For me personally it'd be ideal if it'd also support loading the hover buffer into a different window (like a preview window) - right now there are some places where it assumes the buffer is still associated with the (now closed) floating window, but that's a separate PR

fix: add utils.close_win(winnr) for safer win deletion

---

lua/rust-tools/hover_actions.lua

This is to support scenarios where the buffer that was loaded into the
hover floating window has been moved into another window (for example a
preview window).
Instead of assuming that the buffer is still viewed in the floating
window, we now just use the current window to gather the cursor position.
Example of how I send the contents of the floating hover to a preview
window when hitting the hover keymap twice (instead of entering the
floating window): https://asciinema.org/a/szIURrM5er4XvGyvJXjcPHUAq

fix(hover_actions): use current window to gather cursor position

---

README.md
lua/rust-tools/config.lua
lua/rust-tools/lsp.lua
plugin/rust-tools.vim

This PR adds the option `reload_workspace_from_cargo_toml` (default to `true`, to keep the current behavior) to the config, that controls if the `autocmd BufWritePost */Cargo.toml` should be created.
I fell inclined to create this because of a broken workflow in one of my projects, I need to edit a field in Cargo.toml (that don't impact autocomplete) multiple times. But I also think that always reloading the workspace when editing the Cargo.toml file was triggering too many false-positives.
This PR also removed the `plugin\rust-tools.vim` file, and replace it by a lua function that set the autocmds (including the `BufWritePost */Cargo.toml`, conditionally).

feat(config): allow disabling reload workspace autocmd

---

lua/rust-tools/commands.lua
lua/rust-tools/debuggables.lua
lua/rust-tools/utils/utils.lua

The endpoint of Rust Analyzer textDocument/hover returns commands to run
the program.  It doesn't work for debugging because we have to build and
only then run the program within a debugger.  The arguments are
corrected to achieve that.
Rebased duplicate of https://github.com/simrat39/rust-tools.nvim/pull/226

Fix running a debugger when a debuggee needs input

---

doc/rust-tools.txt
lua/rust-tools/inlay_hints.lua

Fixes the race between inlayHint request and buffer invalidation.
Fixes #249

fix: don't render invalid buffer's inlayHint

---

lua/rust-tools/config.lua
lua/rust-tools/executors/init.lua
lua/rust-tools/lsp.lua

On Windows the lua require calls fail when using slashes, but replacing them with dots works.

fix: lua require paths

---

lua/rust-tools/standalone.lua

Statusline plugins use `filetypes` field to identify whether a given server belongs to a particular filetype or not. This helps them only display relevant server names to the statusline.

Added filetypes field to standalone client config

---

lua/rust-tools/inlay_hints.lua

According to LSP spec, [InlayHint.label](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#inlayHint) can be either a string or an array. Previously, `rust-analyzer` was always returning strings. Most likely after [this recent PR](https://github.com/rust-lang/rust-analyzer/pull/13699) it started returning arrays.
Based on my testing, it seems only inlay hints with `kind` 1 are returning arrays but I am preemptively handling `kind` 2 as well in case it changes in the future.

Fix inlay hints crash when label field is a table

---

lua/rust-tools/debuggables.lua

This prevents a .lua error when not selecting any value in the debuggables selection menu by e.g pressing Esc and closing the menu.

fix(debuggables): check for `nil` value in selection handler

---

lua/rust-tools/inlay_hints.lua

`right_align_padding` is documented in rust-tools' `inlay_hints` but, at least on neovim 0.8, has no effect. This commit explicitly adds padding as spaces.

Respect `right_align_padding`.

---

lua/rust-tools/dap.lua
lua/rust-tools/debuggables.lua

Fixes #313 by filtering test compiler artifacts when debugging tests and bin compiler artifacts when debugging binary. Also adds check if multiple compiler artifacts are available as it is the case in running/debugging multiple test modules.

fix(debuggables): fix choosing debuggable

---

lua/rust-tools/utils/utils.lua

When using [nushell](https://www.nushell.sh), chaining command with `&&` does not work as it is not a supported operator. The replacement for `&&` in nushell is `;`, see [Coming from Bash](https://www.nushell.sh/book/coming_from_bash.html).
This PR adds a check if the current shell (as defined by the environment variable $SHELL) is `nu`. If that's the case, we use `;` as the command chaining operator.
I am not a lua programmer so this is a best effort fix. Please let me know if I can improve anything.

Change command chain operator for nushell

---

lua/rust-tools/config.lua
lua/rust-tools/hover_actions.lua
lua/rust-tools/utils/cache.lua

This allows users to run runnables that were run previously.
Example: Running previous test runnable and not needing to return
the cursor to the function position.
---
Would love feedback on this feature. Things like where should it be, how things are named, configuration options, and any other feedback. I put it into the hover menu because that's what I started to use, but there's also runnables.lua where this may work better or in addition to hover_actions.lua. 
Thank you!

feat: Add last runnables

---

lua/rust-tools/dap.lua

this fixes errors described by #324 and #322 
underlying issue was that unittests are described with `target.kind` == `"lib"` (or bin)  by `cargo test --mesage-format=json`. rust-tools expects that all tests would have `target.kind` == `"test"`. This prevented unittests from being visible. 
We make unittests visible by observing if `profile.test` is set in a cargo test json artifact

adding visibility of unittest binaries

---

lua/rust-tools/inlay_hints.lua

I've been using `rust-tools` for a few months and it's been a great plugin!
However, I noticed that the inlay hints don't work correctly in the presence of multiple clients:
```
Language client log: /Users/mjk/.local/state/nvim/lsp.log
Detected filetype:   rust
1 client(s) attached to this buffer: 
Client: rust_analyzer (id: 2, bufnr: [12])
filetypes:       rust
autostart:       true
root directory:  /Users/mjk/code/rust-tools-test/bar
cmd:             rust-analyzer
1 active client(s) not attached to this buffer: 
Client: rust_analyzer (id: 1, bufnr: [1])
filetypes:       rust
autostart:       true
root directory:  Running in single file mode.
cmd:             rust-analyzer
Configured servers list: rust_analyzer
```
This is because of `cache_render`:
```lua
function M.cache_render(self, …
```

Correctly iterate over multiple clients

---

lua/rust-tools/inlay_hints.lua

A buffer might be unloaded even if it is valid, causing `nvim_buf_get_lines` to return empty array.
Fix #332

fix(#332): Don't render inlay hints for unloaded bufs
